# Generated by Django 6.1.1 on 2026-10-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='thumbnail_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='component',
            name='thumbnail_source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='component',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
